name: Deployment
on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed
jobs:
  deploy:
    timeout-minutes: 60
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
